### ISSUE TITLE
setup code modification (tensorflow or tensorflow-gpu)

### ISSUE THREAD

**Issue by hmkim** [KarchinLab/mhcnuggets#26]
Hi!

Could you modify the setup code for supporting "tensorflow-gpu"?

Please refer to this.
https://stackoverflow.com/questions/55572606/python-setup-py-install-either-tensorflow-or-tensorflow-gpu

**Comment by benjaminalbert** [comment]
Now that TensorFlow 2 is out, the `tensorflow` pip package supports CUDA cards, whereas TensorFlow version <= 1.15 separated `tensorflow` and `tensorflow-gpu` packages (https://www.tensorflow.org/install/gpu).

Because the MHCnuggets requirements does not specify the TensorFlow version, it will default (as of writing this) to TensorFlow 2.6.1, which offers GPU support.

For making MHCnuggets work with TensorFlow 2, please see this: https://github.com/KarchinLab/mhcnuggets/issues/10#issuecomment-958061371
